### ISSUE TITLE
Playing local files shows "advertisement"

### ISSUE THREAD

**Issue by bakzkndd** [vizality-community/spotify-in-discord#2]
### **Description**
When playing a local file through spotify, it does not show the name of the song, artist name or an image. The song does not show as playing and the progress bar does not change whatsoever. None of the controls work either.

### **Steps to reproduce**
1. open spotify and vizality
2. play a .mp3 file through spotify
3. see the spotify player in discord

### **Expected behavior**
Expected to see at least the name of the song, possibly have the artist name filled with "Unknown" if not provided and the image shown as the spotify logo if no image is found for the song. Also expect it to show that it is playing and a progress bar that actually functions. The controls should work too, I can't even skip to the next song now.

Images:

*Spotify player in discord*
![image](https://user-images.githubusercontent.com/50497725/108763287-7d4e0d00-7551-11eb-9412-a0e75e4fe75a.png)

*Spotify player while hovering in discord*
![image](https://user-images.githubusercontent.com/50497725/108763306-84751b00-7551-11eb-8879-5c83c42faba8.png)

*Spotify client*
![image](https://user-images.githubusercontent.com/50497725/108763461-aff80580-7551-11eb-9c85-1bb9efc1d69f.png)

Note: I am using spicetify, although this did not affect anything on the powercord spotify plugin.

**Comment by dperolio** [comment]
Thanks, this has been fixed with e66784f.
