### ISSUE TITLE
I need help downloading it

### ISSUE THREAD

**Issue by OliverBurgstahler** [vizality-community/spotify-in-discord#5]
How to you download it, when I download the zip I don't know what to do, so can someone help me?

**Comment by doggybootsy** [comment]
you shouldn't download the zip, you can't update the plugin if it's done that way

**Comment by doggybootsy** [comment]
You need to cd into your vizalitys plugin folder `/vizality/addons/plugins`
Then run `git clone https://github.com/vizality-community/spotify-in-discord`
Then reloading the client should add the plugin to your plugin list

**Comment by SnuzzleWump** [comment]
Does it work with better discord?

**Comment by doggybootsy** [comment]
No since this is a vizality plugin

**Comment by SnuzzleWump** [comment]
ah ok thanks
